#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
security:
  jwt:
    secret-key: "not-the-production-key"
app:
  website-base-url: "http://localhost:8080"